var annotated_dup =
[
    [ "beman", "namespacebeman.html", [
      [ "execution", "namespacebeman_1_1execution.html", [
        [ "parallel_scheduler_replacement", null, [
          [ "bulk_item_receiver_proxy", "structbeman_1_1execution_1_1parallel__scheduler__replacement_1_1bulk__item__receiver__proxy.html", null ],
          [ "parallel_scheduler_backend", "structbeman_1_1execution_1_1parallel__scheduler__replacement_1_1parallel__scheduler__backend.html", null ],
          [ "receiver_proxy", "structbeman_1_1execution_1_1parallel__scheduler__replacement_1_1receiver__proxy.html", null ]
        ] ],
        [ "as_awaitable_t", "structbeman_1_1execution_1_1as__awaitable__t.html", null ],
        [ "completion_signatures", "structbeman_1_1execution_1_1completion__signatures.html", null ],
        [ "counting_scope", "classbeman_1_1execution_1_1counting__scope.html", "classbeman_1_1execution_1_1counting__scope" ],
        [ "default_domain", "structbeman_1_1execution_1_1default__domain.html", null ],
        [ "dependent_sender_error", "structbeman_1_1execution_1_1dependent__sender__error.html", null ],
        [ "env", "structbeman_1_1execution_1_1env.html", null ],
        [ "get_allocator_t", "structbeman_1_1execution_1_1get__allocator__t.html", null ],
        [ "get_await_completion_adaptor_t", "structbeman_1_1execution_1_1get__await__completion__adaptor__t.html", null ],
        [ "get_delegation_scheduler_t", "structbeman_1_1execution_1_1get__delegation__scheduler__t.html", null ],
        [ "get_env_t", "structbeman_1_1execution_1_1get__env__t.html", null ],
        [ "get_forward_progress_guarantee_t", "structbeman_1_1execution_1_1get__forward__progress__guarantee__t.html", null ],
        [ "get_start_scheduler_t", "structbeman_1_1execution_1_1get__start__scheduler__t.html", null ],
        [ "get_stop_token_t", "structbeman_1_1execution_1_1get__stop__token__t.html", null ],
        [ "indeterminate_domain", "structbeman_1_1execution_1_1indeterminate__domain.html", null ],
        [ "inline_scheduler", "structbeman_1_1execution_1_1inline__scheduler.html", "structbeman_1_1execution_1_1inline__scheduler" ],
        [ "inplace_stop_callback", "classbeman_1_1execution_1_1inplace__stop__callback.html", null ],
        [ "inplace_stop_source", "classbeman_1_1execution_1_1inplace__stop__source.html", null ],
        [ "inplace_stop_token", "classbeman_1_1execution_1_1inplace__stop__token.html", null ],
        [ "is_execution_policy", "structbeman_1_1execution_1_1is__execution__policy.html", null ],
        [ "is_execution_policy< ::beman::execution::parallel_policy >", "structbeman_1_1execution_1_1is__execution__policy_3_01_1_1beman_1_1execution_1_1parallel__policy_01_4.html", null ],
        [ "is_execution_policy< ::beman::execution::parallel_unsequenced_policy >", "structbeman_1_1execution_1_1is__execution__policy_3_01_1_1beman_1_1execution_1_1parallel__unsequenced__policy_01_4.html", null ],
        [ "is_execution_policy< ::beman::execution::sequenced_policy >", "structbeman_1_1execution_1_1is__execution__policy_3_01_1_1beman_1_1execution_1_1sequenced__policy_01_4.html", null ],
        [ "is_execution_policy< ::beman::execution::unsequenced_policy >", "structbeman_1_1execution_1_1is__execution__policy_3_01_1_1beman_1_1execution_1_1unsequenced__policy_01_4.html", null ],
        [ "never_stop_token", "classbeman_1_1execution_1_1never__stop__token.html", null ],
        [ "nostopstate_t", "structbeman_1_1execution_1_1nostopstate__t.html", null ],
        [ "operation_state_tag", "structbeman_1_1execution_1_1operation__state__tag.html", null ],
        [ "parallel_policy", "structbeman_1_1execution_1_1parallel__policy.html", null ],
        [ "parallel_scheduler", "classbeman_1_1execution_1_1parallel__scheduler.html", "classbeman_1_1execution_1_1parallel__scheduler" ],
        [ "parallel_unsequenced_policy", "structbeman_1_1execution_1_1parallel__unsequenced__policy.html", null ],
        [ "prop", "structbeman_1_1execution_1_1prop.html", null ],
        [ "receiver_tag", "structbeman_1_1execution_1_1receiver__tag.html", null ],
        [ "run_loop", "classbeman_1_1execution_1_1run__loop.html", null ],
        [ "schedule_t", "structbeman_1_1execution_1_1schedule__t.html", null ],
        [ "scheduler_tag", "structbeman_1_1execution_1_1scheduler__tag.html", null ],
        [ "sender_adaptor_closure", "structbeman_1_1execution_1_1sender__adaptor__closure.html", null ],
        [ "sender_tag", "structbeman_1_1execution_1_1sender__tag.html", null ],
        [ "sequenced_policy", "structbeman_1_1execution_1_1sequenced__policy.html", null ],
        [ "set_error_t", "structbeman_1_1execution_1_1set__error__t.html", null ],
        [ "set_stopped_t", "structbeman_1_1execution_1_1set__stopped__t.html", null ],
        [ "set_value_t", "structbeman_1_1execution_1_1set__value__t.html", null ],
        [ "simple_counting_scope", "classbeman_1_1execution_1_1simple__counting__scope.html", "classbeman_1_1execution_1_1simple__counting__scope" ],
        [ "start_t", "structbeman_1_1execution_1_1start__t.html", null ],
        [ "stop_callback", "classbeman_1_1execution_1_1stop__callback.html", null ],
        [ "stop_source", "classbeman_1_1execution_1_1stop__source.html", null ],
        [ "stop_token", "classbeman_1_1execution_1_1stop__token.html", null ],
        [ "sync_wait_with_variant_t", "structbeman_1_1execution_1_1sync__wait__with__variant__t.html", null ],
        [ "task", "classbeman_1_1execution_1_1task.html", null ],
        [ "task_scheduler", "classbeman_1_1execution_1_1task__scheduler.html", "classbeman_1_1execution_1_1task__scheduler" ],
        [ "unsequenced_policy", "structbeman_1_1execution_1_1unsequenced__policy.html", null ],
        [ "with_awaitable_senders", "structbeman_1_1execution_1_1with__awaitable__senders.html", null ],
        [ "with_error", "structbeman_1_1execution_1_1with__error.html", null ]
      ] ]
    ] ],
    [ "std", null, [
      [ "common_type< D, ::beman::execution::indeterminate_domain< Domains... > >", "structstd_1_1common__type_3_01D_00_01_1_1beman_1_1execution_1_1indeterminate__domain_3_01Domains_8_8_8_01_4_01_4.html", null ],
      [ "common_type<::beman::execution::indeterminate_domain< Domains... >, D >", "structstd_1_1common__type_3_1_1beman_1_1execution_1_1indeterminate__domain_3_01Domains_8_8_8_01_4_00_01D_01_4.html", null ],
      [ "common_type<::beman::execution::indeterminate_domain< Domains1... >, ::beman::execution::indeterminate_domain< Domains2... > >", "structstd_1_1common__type_3_1_1beman_1_1execution_1_1indeterminate__domain_3_01Domains1_8_8_8_0165f01b763af7a8575fe9cb0bab769a35.html", null ],
      [ "uses_allocator<::beman::execution::task_scheduler, Alloc >", "structstd_1_1uses__allocator_3_1_1beman_1_1execution_1_1task__scheduler_00_01Alloc_01_4.html", null ]
    ] ],
    [ "tst", null, [
      [ "add_set_value", "structtst_1_1add__set__value.html", "structtst_1_1add__set__value" ],
      [ "connector", "structtst_1_1connector.html", null ],
      [ "just_error_t", "structtst_1_1just__error__t.html", null ],
      [ "repeat_effect_unilt_t", "structtst_1_1repeat__effect__unilt__t.html", "structtst_1_1repeat__effect__unilt__t" ],
      [ "resume_after_t", "structtst_1_1resume__after__t.html", null ],
      [ "timer", "classtst_1_1timer.html", "classtst_1_1timer" ],
      [ "when_all_t", "structtst_1_1when__all__t.html", null ]
    ] ],
    [ "receiver", "structreceiver.html", null ],
    [ "shared_wrapper", "structshared__wrapper.html", null ],
    [ "split_t", "structsplit__t.html", null ]
];